version: '3'

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - <PATH-TO-CONFIG>:/data
    ports:
      - <PORT>:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.vaultwarden.loadBalancer.server.port=80"
      #- "traefik.http.routers.vaultwarden.rule=Host(`<URL>`)"
      - "traefik.http.routers.vaultwarden.entrypoints=https"
      - "traefik.http.routers.vaultwarden.tls=true"
      
networks:
  default:
    name: traefik