version: "2.1"
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - <PATH-TO-CONFIG>:/config
    ports:
      - <PORT>:80
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.freshrss.loadBalancer.server.port=80"
      - "traefik.http.routers.freshrss.rule=Host(`<URL>`) || Host(`<URL>`)"
      - "traefik.http.routers.freshrss.entrypoints=https"
      - "traefik.http.routers.freshrss.tls=true"
      
networks:
  default:
    name: traefik