version: '3.2'
services:
    changedetection:
      image: ghcr.io/dgtlmoon/changedetection.io
      container_name: changedetection
      hostname: changedetection
      volumes:
        - <PATH-TO-CONFIG>:/datastore
      environment:
        - TZ=Europe/Warsaw
        - PORT=5000
        - PUID=1000
        - PGID=1000
        - WEBDRIVER_URL=http://browser-chrome:4444/wd/hub
        #- PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000/?stealth=1&--disable-web-security=true
  #      - HTTP_PROXY=socks5h://10.10.1.10:1080
  #      - HTTPS_PROXY=socks5h://10.10.1.10:1080
  #      - NO_PROXY="localhost,192.168.0.0/24"
  #      - BASE_URL=https://mysite.com
  #      - USE_X_SETTINGS=1
  #      - HIDE_REFERER=true
      ports:
        - <PORT>:5000
      restart: unless-stopped
      depends_on:
          browser-chrome:
              condition: service_started
          #playwright-chrome:
              #condition: service_started
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.changedetection.loadBalancer.server.port=5000"
        - "traefik.http.routers.changedetection.rule=Host(`changedetection.home.arpa`)"
        - "traefik.http.routers.changedetection.entrypoints=https"
        - "traefik.http.routers.changedetection.tls=true"


    browser-chrome:
        hostname: browser-chrome
        image: selenium/standalone-chrome-debug:latest
        environment:
            - TZ=Europe/Warsaw
            - VNC_NO_PASSWORD=1
            - SCREEN_WIDTH=200
            - SCREEN_HEIGHT=200
            - SCREEN_DEPTH=24
        volumes:
            - /dev/shm:/dev/shm
        restart: unless-stopped

    #playwright-chrome:
        #hostname: playwright-chrome
        #image: browserless/chrome
        #restart: unless-stopped
        #environment:
            #- TZ=Europe/Warsaw
            #- SCREEN_WIDTH=200
            #- SCREEN_HEIGHT=200
            #- SCREEN_DEPTH=16
            #- ENABLE_DEBUGGER=false
            #- PREBOOT_CHROME=true
            #- CONNECTION_TIMEOUT=3000000
            #- MAX_CONCURRENT_SESSIONS=10
            #- CHROME_REFRESH_TIME=600000
            #- DEFAULT_BLOCK_ADS=true
            #- DEFAULT_STEALTH=true

              #Ignore HTTPS errors, like for self-signed certs
            #- DEFAULT_IGNORE_HTTPS_ERRORS=true
      
networks:
  default:
    name: traefik
    external: true