version: "3.9"
services:
  excalidraw:
    container_name: excalidraw
    healthcheck:
     test: curl -f http://localhost:80/ || exit 1
    image: excalidraw/excalidraw:latest
    ports:
      - <PORT>:80
    restart: on-failure:5
    stdin_open: true
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.excalidraw.loadBalancer.server.port=80"
      #- "traefik.http.routers.excalidraw.rule=Host(`<URL>`)"
      - "traefik.http.routers.excalidraw.entrypoints=https"
      - "traefik.http.routers.excalidraw.tls=true"
      
networks:
  default:
    name: traefik