- name: Watchtower
  hosts: 
    - all
  gather_facts: false
  become: true

  tasks:
    - name: Install Docker SDK for Python
      pip:
        name: "docker" 

    - name: Start Watchtower update
      docker_container:
        name: "{{ watchtower.name }}"
        image: containrrr/watchtower
        state: started
        auto_remove: true
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock 
        env:
          WATCHTOWER_RUN_ONCE: "true"
          WATCHTOWER_CLEANUP: "true"
          WATCHTOWER_NO_STARTUP_MESSAGE: "true"
          WATCHTOWER_NOTIFICATIONS: "shoutrrr"
          WATCHTOWER_NOTIFICATION_URL: "telegram://{{ watchtower.telegram_token }}@telegram/?chats={{ watchtower.telegram_chat_id }}"