---
- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: update

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes
  tags: upgrade

# Optional: Reboot if required
- name: Check if reboot is needed
  stat:
    path: /var/run/reboot-required
  register: reboot_required
  tags: reboot

- name: Reboot system if needed
  ansible.builtin.reboot:
    msg: "System rebooted after updates"
    reboot_timeout: 300
  when: reboot_required.stat.exists
  tags: reboot