version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: 0:0
    ports:
      - <PORT>:80
    volumes:
      - <PATH>:/srv
      - <PATH-TO-CONFIG>:/database.db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.filebrowser.loadBalancer.server.port=80"
      #- "traefik.http.routers.filebrowser.rule=Host(`<URL>`)"
      - "traefik.http.routers.filebrowser.entrypoints=https"
      - "traefik.http.routers.filebrowser.tls=true"
      
networks:
  default:
    name: traefik