- hosts: all
  gather_facts: false
  become: yes

  tasks:
    - name: Install Docker SDK for Python
      pip:
        name: "docker" 

    - name: Start Watchtower update
      docker_container:
        name: "{{ watchtower.name }}"
        image: containrrr/watchtower
        state: started
        auto_remove: true
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock 
        env:
          WATCHTOWER_RUN_ONCE: "true"
          WATCHTOWER_NO_STARTUP_MESSAGE: "true"
          WATCHTOWER_NOTIFICATIONS: "gotify"
          WATCHTOWER_NOTIFICATION_GOTIFY_URL: "{{ watchtower.gotify_ip }}"
          WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN: "{{ watchtower.gotify_token }}"
