---
# - import_tasks: checks.yaml

- name: Update repositories cache and install Restic package
  ansible.builtin.apt:
    name: restic
    update_cache: yes
    state: present

- name: Add SSH key to machine
  ansible.builtin.template:
    src: backup_ssh_key.j2
    dest: "{{ restic_backup__ssh_key_path }}/backup_ssh_key"
    owner: "{{ restic_backup__user }}"
    group: "{{ restic_backup__group }}"
    mode: '0600'
    backup: yes

- name: Ensure python3-paramiko is installed
  ansible.builtin.package:
    name: python3-paramiko
    update_cache: yes
    state: present

- name: Update SSH config with key auto-added to agent
  community.general.ssh_config:
    user: "{{ restic_backup__user }}"
    remote_user: "{{ restic_backup__ssh_user }}"
    host: "{{ restic_backup__ssh_host_alias }}"
    hostname: "{{ restic_backup__ssh_hostname }}"
    identity_file: "{{ restic_backup__ssh_key_path }}/backup_ssh_key"
    add_keys_to_agent: true
    state: present

- name: "Ensure that {{ restic_backup__script_dir }} exists"
  ansible.builtin.file:
    path: "{{ restic_backup__script_dir }}"
    owner: "{{ restic_backup__user }}"
    group: "{{ restic_backup__group }}"
    state: directory
    mode: '0700'

- name: "Copy backup script with owner and permissions to {{ restic_backup__script_dir }}"
  ansible.builtin.copy:
    src: backup_script.sh
    dest: "{{ restic_backup__script_dir }}/backup_script.sh"
    owner: "{{ restic_backup__user }}"
    group: "{{ restic_backup__group }}"
    mode: '0700'

- name: "Template a config.env file to {{ restic_backup__script_dir }}"
  ansible.builtin.template:
    src: config.env.j2
    dest: "{{ restic_backup__script_dir }}/config.env"
    owner: "{{ restic_backup__user }}"
    group: "{{ restic_backup__group }}"
    mode: '0600'