---
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-debian12-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    environment:
      TZ: "Europe/Warsaw"
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
