version: "3"
services:
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - <PORT>:8081
    volumes:
      - <PATH-TO-CONFIG>:/config
      - <PATH-TO-CONFIG>:/downloads
      - <PATH-TO-CONFIG>:/downloads/movies
      - <PATH-TO-CONFIG>:/downloads/series
    environment:
      - STATE_DIR=/config
      #- DOWNLOAD_DIR=/downloads/all
      - CUSTOM_DIRS=true
      - CREATE_CUSTOM_DIRS=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.metube.loadBalancer.server.port=8081"
      #- "traefik.http.routers.metube.rule=Host(`<URL>`)"
      - "traefik.http.routers.metube.entrypoints=https"
      - "traefik.http.routers.metube.tls=true"
      
networks:
  default:
    name: traefik
    external: true