version: '3.3'
services:
  speed:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker
    ports:
        - <PORT>:80
    volumes:
        - <PATH-TO-CONFIG>:/config
    environment:
        - TZ=Europe/Warsaw
        - PGID=1000
        - PUID=1000
        - OOKLA_EULA_GDPR=true
    logging:
        driver: "json-file"
        options:
            max-file: "10"
            max-size: "200k"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.speedtest.loadBalancer.server.port=80"
      #- "traefik.http.routers.speedtest.rule=Host(`<URL>`)"
      - "traefik.http.routers.speedtest.entrypoints=https"
      - "traefik.http.routers.speedtest.tls=true"
      
networks:
  default:
    name: traefik